apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - name: http
      port: 80 # the port exposed by the service
      targetPort: 5000 # the port exposed by the container
  type: LoadBalancer # this will expose the service outside of the cluster
